version: '3.3'

services:
  fluentbit:
    image:  fluent/fluent-bit
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit  -c /fluent-bit/etc/fluent-bit.conf
    ports:
      - 24224:24224
      - "2020:2020"
    networks:
      - exporter-network
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - "/fluent-bit/etc/fluent-bit.conf:/opt/fluent-bit/etc/fluent-bit.conf"
      - "/opt/logs/nginx:/opt/logs/nginx"
      - "/tmp:/var/log/td-agent"
      - "/data/log-go:/data/log-go"
    environment:
      - TZ=Asia/Taipei
networks:
  exporter-network:
    driver: bridge
